name: Bug report
description: Create a report to help us improve

body:
  - type: dropdown
    id: is-regression
    attributes:
      label: Is this a regression?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Please provide a minimal reproduction of the bug
      placeholder: |
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error

  - type: textarea
    id: exception-or-error
    attributes:
      label: Please provide the exception or error you saw
      render: true

  - type: textarea
    id: environment
    attributes:
      label: Please provide the environment you discovered this bug in
      render: true
      placeholder: |
        OS/Device: [e.g. Windows, iPhone6]
        - Browser [e.g. Edge, Safari]
        - Version [e.g. 122]

  - type: textarea
    id: other
    attributes:
      label: Anything else?
